export type MessageBoxProps = {
    id: number;
    img: string;
    description: string;
    desgn: string;
    name: string;
}

export const MessageBoxDetails: MessageBoxProps[] = [
    {
        id: 1,
        img: "https://i.postimg.cc/sgw31sRH/Capture.png",
        description: "Dear Students, Faculty, and Esteemed Members of the Sadguru College of Nursing & Allied Medical Sciences,<br/><br/> It gives me immense pleasure to extend my heartfelt greetings to each one of you as we embark on yet another academic year filled with promise, growth, and dedication to excellence.As the Chairman of Sadguru College of Nursing & Allied Medical Sciences, I am honored to lead an institution that is committed to nurturing the next generation of healthcare professionals.<br/><br/> Our journey has been one of relentless pursuit of quality education, innovative research, and compassionate healthcare delivery.In the ever-evolving landscape of healthcare, our college stands as a beacon of knowledge and a center for holistic development. We take pride in our dedicated faculty who not only impart academic wisdom but also instill values of empathy, integrity, and resilience in our students. These qualities are essential for anyone venturing into the noble field of nursing and allied medical sciences.Our focus remains on creating an environment that fosters curiosity, critical thinking, and a passion for service. We believe that education goes beyond textbooks, and it is our endeavor to provide a well-rounded learning experience that equips our students with the skills and knowledge required to excel in their respective fields.<br/><br/> In the face of global challenges, the role of healthcare professionals has never been more crucial. The world is looking towards us to produce competent, compassionate, and resilient individuals who can contribute meaningfully to the well-being of society. I have full confidence that the Sadguru College of Nursing & Allied Medical Sciences will continue to produce graduates who not only meet but exceed these expectations.<br/><br/> As we embark on this academic year, let us embrace the opportunities for growth and learning. Let us support each other in our individual journeys and collectively contribute to the success and reputation of our institution. Together, we can make a difference in the lives of those we serve.<br/><br/> I extend my best wishes to all students for a successful and fulfilling academic year. May your time at Sadguru College of Nursing & Allied Medical Sciences be marked by achievements, personal growth, and lasting friendships.<br/><br/> Thank you for being part of our esteemed institution.",
        desgn: "Chairman",
        name: "Dr.Pradip Kumar Mohanty"
    },
    {
        id: 2,
        img: "https://i.postimg.cc/rwpvn4vg/Whats-App-Image-2023-11-20-at-1-29-57-PM-qx9p9p51vs7sypahuzadyk8i3j49vfaqrv3ya9vqco.jpg",
        description: "Dear Students, Faculty, and Staff,<br/><br/> It is with immense pleasure and a profound sense of responsibility that I extend my warmest greetings to each member of the Sadguru College of Nursing & Allied Medical Sciences family. <br/><br/> As we embark on a new academic year, I am filled with enthusiasm and optimism for the countless possibilities that lie ahead. Our college has always been a beacon of excellence in healthcare education, and it is my firm belief that this year will be no exception. <br/><br/> Nursing and allied medical sciences are noble professions that require not only academic prowess but also a deep sense of compassion and commitment to humanity. At Sadguru College, we understand the significance of nurturing well-rounded individuals who not only excel in their chosen fields but also carry the torch of empathy and service. <br/><br/> To our esteemed faculty, your dedication to imparting knowledge and shaping the future of our students is truly commendable. Your role in molding young minds and instilling in them the values of integrity, compassion, and continuous learning is pivotal. <br/><br/> To our dear students, you are the heartbeat of this institution. Embrace the challenges that come your way with courage and determination. Remember that each lesson, both inside and outside the classroom, contributes to your growth and development as a healthcare professional. Cherish the learning journey, for it is the foundation upon which your future success will be built. <br/><br/>As we face the global challenges posed by the ever-evolving landscape of healthcare, I encourage each one of you to be proactive in seeking knowledge, innovative in your approaches, and compassionate in your care. Our world needs healthcare professionals who are not only skilled but also deeply human, understanding the needs of patients beyond their medical conditions. <br/><br/> Let this academic year be a testament to our collective commitment to excellence. Together, let us strive to create an environment that fosters learning, mutual respect, and collaboration. <br/><br/> I am confident that with the dedication of our faculty, the enthusiasm of our students, and the support of our staff, Sadguru College of Nursing & Allied Medical Sciences will continue to shine brightly as a center of academic excellence and compassionate healthcare. <br/><br/> Wishing you all a fulfilling and successful academic year ahead.",
        desgn: "Principal",
        name: "Mrs. Santoshini Jena"
    }
]