export type MessageBoxProps = {
    id: number;
    img: string;
    description: string;
    desgn: string;
    name: string;
}

export const MessageBoxDetails: MessageBoxProps[] = [
    {
        id: 1,
        img: "https://res.cloudinary.com/dbivz5ppm/image/upload/v1735985076/About%20Us/emjz2vo2ombrqnbnrhwd.webp",
        description: "Dear Students, Faculty, and Esteemed Members of the Sadguru College of Nursing & Allied Medical Sciences,<br/><br/> It gives me immense pleasure to extend my heartfelt greetings to each one of you as we embark on yet another academic year filled with promise, growth, and dedication to excellence. As the Chairman of Sadguru College of Nursing & Allied Medical Sciences, I am honored to lead an institution that is committed to nurturing the next generation of healthcare professionals.<br/><br/> Our journey has been one of relentless pursuit of quality education, innovative research, and compassionate healthcare delivery. In the ever-evolving landscape of healthcare, our college stands as a beacon of knowledge and a center for holistic development. We take pride in our dedicated faculty who not only impart academic wisdom but also instill values of empathy, integrity, and resilience in our students. These qualities are essential for anyone venturing into the noble field of nursing and allied medical sciences. Our focus remains on creating an environment that fosters curiosity, critical thinking, and a passion for service. We believe that education goes beyond textbooks, and it is our endeavor to provide a well-rounded learning experience that equips our students with the skills and knowledge required to excel in their respective fields.<br/><br/> In the face of global challenges, the role of healthcare professionals has never been more crucial. The world is looking towards us to produce competent, compassionate, and resilient individuals who can contribute meaningfully to the well-being of society. I have full confidence that the Sadguru College of Nursing & Allied Medical Sciences will continue to produce graduates who not only meet but exceed these expectations.<br/><br/> As we embark on this academic year, let us embrace the opportunities for growth and learning. Let us support each other in our individual journeys and collectively contribute to the success and reputation of our institution. Together, we can make a difference in the lives of those we serve.<br/><br/> I extend my best wishes to all students for a successful and fulfilling academic year. May your time at Sadguru College of Nursing & Allied Medical Sciences be marked by achievements, personal growth, and lasting friendships.<br/><br/> Thank you for being part of our esteemed institution.",
        desgn: "Chairman, Sadguru College of Nursing & Allied Medical Sciences",
        name: "Dr. Pradip Kumar Mohanty"
    },
    {
        id: 2,
        img: "https://res.cloudinary.com/dbivz5ppm/image/upload/v1735985076/About%20Us/uwh2t1gyboyxhh1ovqur.webp",
        description: "Dear Students, Faculty, and Staff,<br/><br/> It is with immense pleasure and a profound sense of responsibility that I extend my warmest greetings to each member of the Sadguru College of Nursing & Allied Medical Sciences family. <br/><br/> As we embark on a new academic year, I am filled with enthusiasm and optimism for the countless possibilities that lie ahead. Our college has always been a beacon of excellence in healthcare education, and it is my firm belief that this year will be no exception. <br/><br/> Nursing and allied medical sciences are noble professions that require not only academic prowess but also a deep sense of compassion and commitment to humanity. At Sadguru College, we understand the significance of nurturing well-rounded individuals who not only excel in their chosen fields but also carry the torch of empathy and service. <br/><br/> To our esteemed faculty, your dedication to imparting knowledge and shaping the future of our students is truly commendable. Your role in molding young minds and instilling in them the values of integrity, compassion, and continuous learning is pivotal. <br/><br/> To our dear students, you are the heartbeat of this institution. Embrace the challenges that come your way with courage and determination. Remember that each lesson, both inside and outside the classroom, contributes to your growth and development as a healthcare professional. Cherish the learning journey, for it is the foundation upon which your future success will be built. <br/><br/>As we face the global challenges posed by the ever-evolving landscape of healthcare, I encourage each one of you to be proactive in seeking knowledge, innovative in your approaches, and compassionate in your care. Our world needs healthcare professionals who are not only skilled but also deeply human, understanding the needs of patients beyond their medical conditions. <br/><br/> Let this academic year be a testament to our collective commitment to excellence. Together, let us strive to create an environment that fosters learning, mutual respect, and collaboration. <br/><br/> I am confident that with the dedication of our faculty, the enthusiasm of our students, and the support of our staff, Sadguru College of Nursing & Allied Medical Sciences will continue to shine brightly as a center of academic excellence and compassionate healthcare. <br/><br/> Wishing you all a fulfilling and successful academic year ahead.",
        desgn: "Principal, Sadguru College of Nursing & Allied Medical Sciences",
        name: "Mrs. Santoshini Jena"
    },
    {
        id: 3,
        img: "https://res.cloudinary.com/dajq9hekb/image/upload/f_auto,q_auto/t0qtisuj4wpxh0ddjxs3",
        description: "With great joy and a deep sense of responsibility, I welcome you all to a new academic year at Sadguru College of Nursing & Allied Medical Sciences. As the Managing Trustee, it is a privilege to be part of an institution that is dedicated to shaping the future of healthcare through excellence in education, innovation, and service. .<br/><br/>At Sadguru College, we believe that true education is not just about acquiring knowledge but about building character, developing empathy, and fostering a passion for service. The field of healthcare demands professionals who are not only skilled but also compassionate and resilient. Our goal is to nurture individuals who will make a meaningful impact in the lives of others through their dedication and expertise. .<br/><br/>Our faculty and staff play a crucial role in this mission, providing students with the guidance, mentorship, and encouragement they need to excel. Beyond academics, we focus on creating a supportive learning environment that instills confidence, critical thinking, and a commitment to ethical practice. .<br/><br/>As the world continues to evolve, so do the challenges in healthcare. Now, more than ever, we need professionals who are prepared to meet these challenges with courage and determination. I have no doubt that our students will rise to the occasion, carrying forward the values and legacy of Sadguru College. .<br/><br/>As we embark on this new academic journey together, let us embrace opportunities, strive for excellence, and support one another in achieving our shared vision. I extend my best wishes to all students and look forward to seeing them grow into successful and compassionate healthcare professionals.",
        desgn: "Managing Trusty, Director of Jay Bharat Spices",
        name: "Mrs Nandita Panda"

    },
    {
        id: 4,
        img: "https://res.cloudinary.com/dajq9hekb/image/upload/f_auto,q_auto/vezag0uy4fd4q0hhfs90",
        description: "It is with great honor and enthusiasm that I extend my warmest greetings to all as we step into a new academic year at Sadguru College of Nursing & Allied Medical Sciences. As the Managing Trustee, I take immense pride in being part of an institution that is dedicated to excellence in healthcare education, research, and service.<br/><br/>Our mission has always been to empower students with not just knowledge but the values and skills necessary to excel in the noble profession of healthcare. At Sadguru College, we believe that true learning goes beyond textbooks—it is about developing a strong sense of responsibility, empathy, and resilience. These qualities are the foundation of a great healthcare professional. .<br/><br/>We are privileged to have a team of dedicated faculty members who not only impart academic expertise but also mentor our students to become compassionate caregivers and ethical professionals. Our commitment remains unwavering in fostering a learning environment that promotes critical thinking, hands-on experience, and a passion for service. .<br/><br/>In today's rapidly evolving healthcare landscape, the role of well-trained professionals is more crucial than ever. Our students carry the responsibility of shaping the future of healthcare, and I have no doubt that they will rise to the challenge with confidence and dedication. .<br/><br/>As we begin this academic journey together, let us embrace new opportunities, support one another, and uphold the legacy of excellence that defines Sadguru College of Nursing & Allied Medical Sciences. I wish all our students a fulfilling and successful year ahead, filled with growth, achievements, and meaningful experiences.",
        desgn: "Managing Trustee , MD of Jay Bharat Spices",
        name: "Mr Susant Kumar Panda",
    },
    {
        id: 5,
        img: "https://res.cloudinary.com/dajq9hekb/image/upload/f_auto,q_auto/cugwrxl6mgdmofwda3ik",
        description: "It is with immense pride and joy that I extend my warmest greetings to all as we step into another promising academic year at Sadguru College of Nursing & Allied Medical Sciences. As the Managing Trustee, I feel privileged to be part of an institution that upholds the highest standards of education, innovation, and service in the healthcare sector.<br/><br/>At Sadguru College, our commitment has always been to nurture not just skilled professionals but compassionate caregivers who will make a meaningful impact in the world of healthcare. The ever-evolving medical landscape demands individuals who are not only academically proficient but also empathetic, resilient, and dedicated to lifelong learning. It is this holistic approach that sets our institution apart.<br/><br/>We take immense pride in our esteemed faculty, whose unwavering dedication shapes the future of our students. Their mentorship goes beyond academics, fostering values of integrity, commitment, and ethical practice. Our mission remains steadfast—to create an environment that encourages curiosity, critical thinking, and a passion for serving humanity.<br/><br/>In today’s world, healthcare professionals are at the forefront of addressing global challenges. The responsibility we bear is immense, and the need for compassionate, competent professionals has never been greater. I have full confidence that our students will rise to the occasion, embracing every challenge with courage and determination. <br/><br/>As we embark on this new academic year, let us strive for excellence, support one another, and continue to uphold the values that define Sadguru College of Nursing & Allied Medical Sciences. May this year bring new achievements, personal growth, and meaningful connections that last a lifetime. <br/><br/>Wishing all our students great success in their journey ahead.",
        desgn: "Managing Trusty , Medical Superintendent , Sadguru Hospital",
        name: "Dr. Samita Mohanty"

    },
]
